version: '3'
services: 
    my-app :
        build:
            context: .
            dockerfile: Dockerfile.dev
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        image: my-app
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]